
# hardware

Hello, can you create a brass M8x45mm Hex Head screw, add a small fillet to all the edges, then add a joint origin to the top face?

Can you create a similar component, but this time for an stainless steel M12x30mm Hex Head screw?

Hello, can you create a brass M8x20mm Socket Head screw, with a small chamfer on all the edges, then add a joint origin on the top face?

Hello, can you create an M8x40mm hex head bolt, with a .5mm chamfer on all edges?
Hello, can you create a black oxide M8x35mm hex head bolt with a small chamfer on all the edges and a joint origin on the top. Then create the associated nut and washer for the bolt, both should also have joint origins. These should all be in a parent container called M8-Hardware. Use standard dimensions for all the components.


# random cubes
Hello, can you generate 30 rectangles with random sizes between 10 and 20mm. The rectangles should be quite close together so they are overlapping. Then extrude each profile by a random amount between 10 and 30mm.


# keyboard

I am designing a common TKL keyboard. It will have a main body, which should be draw as a rectangle, then extruded into a solid. On top of the body, you should create another sketch for the keys. Each key profile should be drawn as square or rectangle depending on the key. For example: number and letter keys are square, but space bar and shift keys are rectangular. Each key should be in the correct x,y position for a TKL QWERTY keyboard. You may want to create a separate sketch for each row or other logical grouping you think makes sense. Make sure to include all the keys. There should be a slight gap between each key. The keys should be extrude-joined into the body, protruding through the top, if the key sketches and the body sketch have the same z position, the keys need to be extruded at least as thick as the body. For body size, key size, key height, and key spacing, use common values for a typical TKL keyboard.




# vase
Can you create a vase. It should have a very detailed, highly contoured profile, and you should probably use the spline tool. Make sure the walls are sufficiently far from the Z axis. The walls should be a few mm thick.


Hello, can you create a new component called shapes, then create a basic 4 point spline in the sketch?


# shapes
Cuboctahedron

Hello, can you create Great dodecahedron. You should Create a new component and sketch. The create the Great dodecahedron vertices and edges used sketch lines. Remember sketch object can be 3d.

# Rhombicuboctahedron 
Hello, Please create a Rhombicuboctahedron in the current design. Start by creating a component and sketch, they should have meaningful names. Then create all the faces by drawing the edges and vertices with sketchLines or any other type of sketch geometry you think is appropriate. Remember all sketch geometry can be 3d. The overall height of the Rhombicuboctahedron should be about 100mm, although the exact dimensions are not that important. 


# kind of worked, wrong geometry
# Great triambic icosahedron
Hello, Please create a Great triambic icosahedron in the current design. Start by querying the document structure, then create a component and sketch, they should have meaningful names. Create all the faces by drawing the edges and vertices with sketchLines. Remember all sketch geometry can be 3d. The overall height of the Great triambic icosahedron should be about 100mm, although the exact dimensions are not that important. 


# Great triambic icosahedron
Hello, Please create a crossed triangular antiprism in the current design. Start by querying the document structure, then create a component and sketch, they should have meaningful names. Create all the faces by drawing the edges and vertices with sketchLines. Remember all sketch geometry can be 3d. The overall height should be about 100mm, although the exact dimensions are not that important. 



# fail Truncated octahedron
Hello, Please create a Truncated octahedron in the current design. Create a component and sketch, then create the edges and vertices with sketch objects, such as sketchLines, sketchPoints, polygons, etc. he overall height of the polyhedron should be about 100mm, although the exact dimensions are not that important. After you have created the sketch lines, add a 5mm diameter pipe feature to each line. Please give the component and sketch meaning full names. 



# Hardware 
Create a standard M8x50mm Socket Head Screw. Add a small fillet to the vertical edges and a small chamfer to horizontal edges. You should put this component in another component called M8-Hardware. 


# screw copy
Hello, I would like you to create an M8, M12 and M16 socket head screw based on the M6 screw in the current design. Start by creating 3 "new copies" of the M6 screw component. Each new component should be spaced 15mm from the previous. Then, rename and modify the parameters, so each of the new component's dimension are set to to the correct values for their respective screw types.


# screw copy
Hello, Create a M8, M10, M12, and M16 socket head screw based on the M6 screw in the current design. Start by creating 5 "new copies" of the M6 screw component. After creating the new components, arrange them in order of diameter, such that the each component does not overlap with the adjacent components. After moving the components, rename and modify the parameters so each of the new component's dimensions are set to to the correct values for their respective screw types. Make sure to adjust the parameter values in the sketches first, the body create features, and finally cut features. Also, the fillets, chamfers and shaft length extrude should be set proportionally to the screw size. Finally set the appearance on the screws to the following: The M10 should be some type of zinc. The M8, M16, should be some type of black oxide steel. The M6, M10, and M12 should be some type of stainless steel. 


# NEMA 17
Hello, I would like to create a mounting plate for a NEMA 17 stepper motor.  

Isogrid
Hello, I would like to create a section of Isogrid, that will be 3d printed. The section should be arranged as a hexagon with an approximate width of 100mm. It will contain 24 total triangular cutout sections and 7 total intersection points. After creating the component, you should start with a sketch on the xy plane. Think deeply about the best way for you to accomplish this. 



Please create a Gyroelongated triangular cupola. You should create each face by drawing the vertices with sketchLine objects. Remember all sketch geometry is 3d. The Gyroelongated triangular cupola should be about 100m tall. Begin by creating a component and sketch.


# OLD hardware isolation
Hello, Please hide every occurrence other than fastening hardware or their container occurrences? Fastening hardware includes all occurrences that contain words like M4, M5, M6, M8, screw, bolt, washer, nut, and hardware. Hardware containers usually have the phrase "hardware-container" in the name, and all bodies inside should be visible. Make sure you don't hide a hardware occurrence's ancestor occurrence, since they may be nested many levels deep. You should only hide the actual body in a occurrence, not the occurrence itself. All top level occurrences, and any occurrence that is an assembly or container should remain visible. Also, Hardware will never be made out of aluminum, and all plates should be hidden.



# hardware isolation
I would like to set all bodies relating to hardware visible, specificly: hardware, screws, bolts, nuts, washers, etc... Also components with the terms Thread, or M8 show be included. Can you first query the names of all the components. Then run a query that make all bodies visible whose parent component name includes relevent hardware related terms

